baseURL: "http://localhost:1313/"
title: "Guardian Project"

DefaultContentLanguage: "en"
Paginate: 20 # this is set low for demonstrating with dummy content. Set to a higher number
pluralizeListTitles: false
enableRobotsTXT: true

permalinks:
  blog: /:year/:month/:day/:title/

frontmatter:
  date: ["date", ":filename", ":git", ":default"]
  lastmod: ["lastmod", ":fileModTime", ":git", ":default"]

# ensure this stuff is all disabled, key bits have also been deleted
googleAnalytics: ""

sitemap:
  changefreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - name: about
      weight: -10
    - name: apps
      weight: 1
    - name: code
      weight: 1
    - name: archive
      weight: 2
    - name: contact
      weight: 10
    - name: podcast
      url: "https://guardianproject.info/podcast/"
      parent: about
      weight: 2
    - name: "Toot @guardianproject@librem.one"
      url: "https://social.librem.one/@guardianproject"
      parent: contact
    - name: "Tweet @guardianproject"
      url: "https://twitter.com/guardianproject"
      parent: contact

languages:
  en: {weight: 1}

Params:
  since: 2009
  logo: Guardian_Project_LogoMark_Full_Color.svg
  wordlogo: Guardian_Project_Horizontal_Logo_Full_Color.svg
  rss: true
  favicon: Guardian_Project_LogoMark_Full_Color.svg
  description: "People, Apps and Code You Can Trust"
  mastodon: "https://social.librem.one/@guardianproject"
  twitter: "guardianproject"
  github: "guardianproject"
  gitlab: "guardianproject"
  liberapay: "GuardianProject"
  matrix: "#guardianproject:matrix.org"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class: "bg-black"
  featured_image: "gpnewlogo2025.png"
  recent_posts_number: 2
  mainSections: ["posts"]
  homeTitle: " "

# disable all the external Javascript, etc services from theme
  selfHosted: true
  useHLJS: false
