baseURL: "http://localhost:1313/"
title: "Guardian Project"

DefaultContentLanguage: "en"
Paginate: 20
pluralizeListTitles: false
enableRobotsTXT: true

module:
  imports:
    - path: github.com/writeonlycode/hugo-up-business

permalinks:
  blog: /:year/:month/:day/:title/

frontmatter:
  date: ["date", ":filename", ":git", ":default"]
  lastmod: ["lastmod", ":fileModTime", ":git", ":default"]

# ensure this stuff is all disabled, key bits have also been deleted
googleAnalytics: ""

sitemap:
  changefreq: "monthly"
  priority: 0.5
  filename: "sitemap.xml"

markup:
  goldmark:
    renderer:
      unsafe: true

menu:
  main:
    - identifier: about
      name: About
      url: /
      weight: -10
    - identifier: apps
      name: Apps
      url: /apps/
      weight: 1
    - identifier: code
      name: Code
      url: /code/
      weight: 2
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 3
    - identifier: archive
      name: Archive
      url: /archive/
      weight: 4
    - identifier: contact
      name: Contact
      url: /contact/
      weight: 10

languages:
  en: {weight: 1}

Params:
  since: 2009
  logo: Guardian_Project_LogoMark_Full_Color.svg
  wordlogo: Guardian_Project_Horizontal_Logo_Full_Color.svg
  rss: true
  favicon: Guardian_Project_LogoMark_Full_Color.svg
  description: "People, Apps and Code You Can Trust"
  copyright: "© Guardian Project, 2009-2026. Licensed under CC-BY."
  mastodon: "https://social.librem.one/@guardianproject"
  twitter: "guardianproject"
  github: "guardianproject"
  gitlab: "guardianproject"
  liberapay: "GuardianProject"
  matrix: "#guardianproject:matrix.org"
  featured_image: "gpnewlogo2025.png"
  recent_posts_number: 2
  mainSections: ["blog"]
  homeTitle: " "
  colors:
    primary: "#04A052"
    secondary: "#1a1a2e"
    tertiary: "#f0faf4"
  social:
    twitter: "https://social.librem.one/@guardianproject"
    facebook: "https://github.com/guardianproject"
  contact:
    - "contact@guardianproject.info"
    - "https://matrix.to/#/#guardianproject:matrix.org"

  selfHosted: true
  useHLJS: false
